Packet => size payload
  size => INT32
  payload => Request | Response

Message => offset size crc magic_byte attributes key value
  offset => INT64
  size => INT32
  crc => INT32
  magic_byte => INT8
  attributes => INT8
  key => BYTES
  value => BYTES

# embedded in 'BYTES' content of
# JoinGroupRequestV0.group_protocol.protocol_metadata
# JoinGroupResponseV0.members.protocol_metadata
ConsumerGroupProtocolMetadata => version [topics] user_data
  version => INT16
  topics => STRING
  user_data => BYTES

## embedded in 'BYTES' content of
## SyncGroupRequestV0.group_assignment.member_assignment
ConsumerGroupMemberAssignment => version [partition_assignments] user_data
  version => INT16
  partition_assignments => topic [partitions]
    topic => STRING
    partitions => INT32
  user_data => BYTES
