## Reference: https://cwiki.apache.org/confluence/display/KAFKA/A+Guide+To+The+Kafka+Protocol#AGuideToTheKafkaProtocol
## This is the source for code generation.

Packet => Size Payload
  Size => INT32
  Payload => Request | Response

Request => ApiKey ApiVersion CorrelationId ClientId RequestMessage
  ApiKey => INT16
  ApiVersion => INT16
  CorrelationId => INT32
  ClientId => STRING
  RequestMessage => ProduceRequest | FetchRequest | OffsetRequest | MetadataRequest | OffsetCommitRequestV0 | OffsetCommitRequestV1 | OffsetCommitRequestV2 | OffsetFetchRequest | GroupCoordinatorRequest | JoinGroupRequest | HeartbeatRequest | LeaveGroupRequest | SyncGroupRequest | DescribeGroupsRequest | ListGroupsRequest | SaslHandshakeRequest

Response => CorrelationId ResponseMessage
  CorrelationId => INT32
  ResponseMessage => ProduceResponse | FetchResponse | OffsetResponse | MetadataResponse | OffsetCommitResponse | OffsetFetchResponse | GroupCoordinatorResponse | JoinGroupResponse | HeartbeatResponse | LeaveGroupResponse | SyncGroupResponse | DescribeGroupsResponse | ListGroupsResponse | SaslHandshakeResponse

Message => Offset MessageSize Crc MagicByte Attributes Key Value
  Offset => INT64
  MessageSize => INT32
  Crc => INT32
  MagicByte => INT8
  Attributes => INT8
  Key => BYTES
  Value => BYTES

MetadataRequest => [TopicName]
  TopicName => STRING

MetadataResponse => [Broker] [TopicMetadata]
  Broker => NodeId Host Port
  NodeId => INT32
  Host => STRING
  Port => INT32
  TopicMetadata => ErrorCode TopicName [PartitionMetadata]
  PartitionMetadata => ErrorCode Partition Leader Replicas Isr
  Partition => INT32
  Leader => INT32
  Replicas => [INT32]
  Isr => [INT32]
  ErrorCode => INT16
  TopicName => STRING

ProduceRequest => RequiredAcks Timeout [TopicMessageSet]
  TopicMessageSet => TopicName [PartitionMessageSet]
  PartitionMessageSet => Partition MessageSetSize [Message]
  RequiredAcks => INT16
  Timeout => INT32
  Partition => INT32
  MessageSetSize => INT32
  TopicName => STRING

ProduceResponse => [ProduceResponseTopic]
  ProduceResponseTopic => TopicName [ProduceResponsePartition]
  ProduceResponsePartition => Partition ErrorCode Offset
  TopicName => STRING
  Partition => INT32
  ErrorCode => INT16
  Offset => INT64

FetchRequest => ReplicaId MaxWaitTime MinBytes [FetchRequestTopic]
  FetchRequestTopic => TopicName [FetchRequestPartition]
  FetchRequestPartition => Partition FetchOffset MaxBytes
  ReplicaId => INT32
  MaxWaitTime => INT32
  MinBytes => INT32
  TopicName => STRING
  Partition => INT32
  FetchOffset => INT64
  MaxBytes => INT32

FetchResponse => [FetchResponseTopic]
  FetchResponseTopic => TopicName [FetchResponsePartition]
  FetchResponsePartition => Partition ErrorCode HighWatermarkOffset MessageSetSize [Message]
  TopicName => STRING
  Partition => INT32
  ErrorCode => INT16
  HighWatermarkOffset => INT64
  MessageSetSize => INT32

OffsetRequest => ReplicaId [OffsetRequestTopic]
  OffsetRequestTopic => TopicName [OffsetRequestPartition]
  OffsetRequestPartition => Partition Time MaxNumberOfOffsets
  ReplicaId => INT32
  TopicName => STRING
  Partition => INT32
  Time => INT64
  MaxNumberOfOffsets => INT32

OffsetResponse => [TopicOffsets]
  TopicOffsets => TopicName [PartitionOffsets]
  PartitionOffsets => Partition ErrorCode [Offset]
  TopicName => STRING
  Partition => INT32
  ErrorCode => INT16
  Offset => INT64

GroupCoordinatorRequest => GroupId
  GroupId => STRING

GroupCoordinatorResponse => ErrorCode CoordinatorId CoordinatorHost CoordinatorPort
  ErrorCode => INT16
  CoordinatorId => INT32
  CoordinatorHost => STRING
  CoordinatorPort => INT32

OffsetCommitRequestV0 => ConsumerGroupId [OCReqV0Topic]
  OCReqV0Topic => TopicName [OCReqV0Partition]
  OCReqV0Partition => Partition Offset Metadata
  ConsumerGroupId => STRING
  TopicName => STRING
  Partition => INT32
  Offset => INT64
  Metadata => STRING

OffsetCommitRequestV1 => ConsumerGroupId ConsumerGroupGenerationId ConsumerId [OCReqV1Topic]
  OCReqV1Topic => TopicName [OCReqV1Partition]
  OCReqV1Partition => Partition Offset TimeStamp Metadata
  ConsumerGroupId => STRING
  ConsumerGroupGenerationId => INT32
  ConsumerId => STRING
  TopicName => STRING
  Partition => INT32
  Offset => INT64
  TimeStamp => INT64
  Metadata => STRING

OffsetCommitRequestV2 => ConsumerGroupId ConsumerGroupGenerationId ConsumerId RetentionTime [OCReqV2Topic]
  OCReqV2Topic => TopicName [OCReqV2Partition]
  OCReqV2Partition => Partition Offset Metadata
  ConsumerGroupId => STRING
  ConsumerGroupGenerationId => INT32
  ConsumerId => STRING
  RetentionTime => INT64
  TopicName => STRING
  Partition => INT32
  Offset => INT64
  Metadata => STRING

OffsetCommitResponse => [OCRspTopic]
  OCRspTopic => TopicName [OCRspPartition]
  OCRspPartition => Partition ErrorCode
  TopicName => STRING
  Partition => INT32
  ErrorCode => INT16

OffsetFetchRequest => ConsumerGroup [OFReqTopic]
  OFReqTopic => TopicName [Partition]
  ConsumerGroup => STRING
  TopicName => STRING
  Partition => INT32

OffsetFetchResponse => [TopicOffset]
  TopicOffset => TopicName [PartitionOffset]
  PartitionOffset => Partition Offset Metadata ErrorCode
  TopicName => STRING
  Partition => INT32
  Offset => INT64
  Metadata => STRING
  ErrorCode => INT16

JoinGroupRequest => GroupId SessionTimeout MemberId ProtocolType [GroupProtocol]
  GroupId => STRING
  SessionTimeout => INT32
  MemberId => STRING
  ProtocolType => STRING
  GroupProtocol => ProtocolName ProtocolMetadata
    ProtocolName => STRING
    ProtocolMetadata => BYTES

JoinGroupResponse => ErrorCode GenerationId ProtocolName LeaderId MemberId [GroupMemberMetadata]
  ErrorCode => INT16
  GenerationId => INT32
  ProtocolName => STRING
  LeaderId => STRING
  MemberId => STRING

GroupMemberMetadata => MemberId ProtocolMetadata
  MemberId => STRING
  ProtocolMetadata => BYTES

# embeded in 'BYTES' content of
# JoinGroupRequest.GroupProtocol.ProtocolMetadata
# JoinGroupResponse.Members.ProtocolMetadata
ConsumerGroupProtocolMetadata => Version [TopicName] UserData
  Version => INT16
  TopicName => STRING
  UserData => BYTES

SyncGroupRequest => GroupId GenerationId MemberId [GroupAssignment]
  GroupId => STRING
  GenerationId => INT32
  MemberId => STRING

GroupAssignment => MemberId MemberAssignment
  MemberId => STRING
  MemberAssignment => BYTES

## embeded in 'BYTES' content of
## SyncGroupRequest.GroupAssignment.MemberAssignment
ConsumerGroupMemberAssignment => Version [ConsumerGroupPartitionAssignment] UserData
  Version => INT16
  ConsumerGroupPartitionAssignment => TopicName [Partition]
    TopicName => STRING
    Partition => INT32
  UserData => BYTES

SyncGroupResponse => ErrorCode MemberAssignment
  ErrorCode => INT16
  MemberAssignment => BYTES

HeartbeatRequest => GroupId GenerationId MemberId
  GroupId => STRING
  GenerationId => INT32
  MemberId => STRING

HeartbeatResponse => ErrorCode
  ErrorCode => INT16

LeaveGroupRequest => GroupId MemberId
  GroupId => STRING
  MemberId => STRING

LeaveGroupResponse => ErrorCode
  ErrorCode => INT16

ListGroupsRequest =>

ListGroupsResponse => ErrorCode [GroupInfo]
  ErrorCode => INT16
  GroupInfo => GroupId ProtocolType
    GroupId => STRING
    ProtocolType => STRING

DescribeGroupsRequest => [GroupId]
  GroupId => STRING

DescribeGroupsResponse => [GroupDescription]
  GroupDescription => ErrorCode GroupId State ProtocolType Protocol [GroupMemberDescription]
  ErrorCode => INT16
  GroupId => STRING
  State => STRING
  ProtocolType => STRING
  Protocol => STRING
  GroupMemberDescription => MemberId ClientId ClientHost MemberMetadata MemberAssignment
    MemberId => STRING
    ClientId => STRING
    ClientHost => STRING
    MemberMetadata => BYTES
    MemberAssignment => BYTES

SaslHandshakeRequest => Mechanism
  Mechanism => STRING

SaslHandshakeResponse => ErrorCode [EnabledMechanisms]
  ErrorCode => INT16
  EnabledMechanisms => STRING
